<!--this page needs ui for the date picker-->
<!--<link href="Common/jquery-ui-1.11.4.smoothness/jquery-ui.min.css" rel="stylesheet" />-->
<!--Scroll to Top CSS-->
<link href="Common/ScrollToTop/top.css" rel="stylesheet" />
<!--font awesome-->
<link href="Common/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
<!--frmListManager Common CSS-->
<link href="Common/css/frmListManager.css" rel="stylesheet" />
<!-- Include Bootstrap Datepicker -->
<link rel="stylesheet" href="Common/css/bootstrap-datepicker.css" />
<link rel="stylesheet" href="Common/css/bootstrap-datepicker3.min.css" />
<link rel="stylesheet" href="Common/css/bootstrap-datetimepicker.min.css" />

