'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ContractEntry
    
    '''<summary>
    '''frmContractEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmContractEntry As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btnHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHidden As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtSessions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSessions As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtRecID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litContractID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litContractID As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblPatientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litShowPatientData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litShowPatientData As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPaymentPosting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPaymentPosting As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGenerateClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerateClaim As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnContractStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContractStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPaymentHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPaymentHistory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnViewNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewNotes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNotes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtChartNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChartNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAccountNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dteEndContractDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteEndContractDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEndReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dteContractDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteContractDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlDoctors_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDoctors_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlTransactionCodes_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransactionCodes_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlStatus_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAccount_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccount_ID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPreviousContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPreviousContract As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPatientInitialBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPatientInitialBalance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dtePatientFirstPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtePatientFirstPay As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPatientInitialPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPatientInitialPayment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPatientDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPatientDiscount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPatientMonthlyPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPatientMonthlyPayment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPatientBillingFrequency_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPatientBillingFrequency_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dolPatientAmountBilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPatientAmountBilled As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPatientContractMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPatientContractMonths As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPatientRemainingMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPatientRemainingMonths As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPatientRemainingBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPatientRemainingBalance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkPrintMonthlyInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrintMonthlyInvoice As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtname_first control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtname_first As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtname_mid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtname_mid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtname_last control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtname_last As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtaddr_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaddr_other As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtaddr_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaddr_street As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtaddr_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaddr_city As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtaddr_state control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaddr_state As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtaddr_zip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaddr_zip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGender As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dteDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDOB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPrimaryInsurancePlans_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrimaryInsurancePlans_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dolPrimaryCoverageAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPrimaryCoverageAmt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPrimaryInitialPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPrimaryInitialPayment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPrimaryInstallmentAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPrimaryInstallmentAmt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPrimaryBillingFrequency_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrimaryBillingFrequency_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dolPrimaryClaim_Amount_Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPrimaryClaim_Amount_Initial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPrimaryClaim_Amount_Installment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPrimaryClaim_Amount_Installment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPrimaryRemainingBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPrimaryRemainingBalance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolPrimaryAmountBilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolPrimaryAmountBilled As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkPrintMonthlyClaimPrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrintMonthlyClaimPrimary As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblPrimaryInsuranceProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrimaryInsuranceProvider As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtInsured_name_first control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_first As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_name_mid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_mid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_name_last control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_last As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_name_suffx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_suffx As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_street As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_city As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_state control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_state As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_zip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_zip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlInsured_Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInsured_Gender As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dteInsured_Date_Birth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteInsured_Date_Birth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEmployer_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployer_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dteDate_Effective control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDate_Effective As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dteDate_Canceled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDate_Canceled As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGroup_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroup_Number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPolicy_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolicy_Number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolLifetimeMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolLifetimeMax As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlSecondaryInsurancePlans_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSecondaryInsurancePlans_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dolSecondaryCoverageAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolSecondaryCoverageAmt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolSecondaryInitialPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolSecondaryInitialPayment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolSecondaryInstallmentAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolSecondaryInstallmentAmt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlSecondaryBillingFrequency_vw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSecondaryBillingFrequency_vw As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dolSecondaryClaim_Amount_Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolSecondaryClaim_Amount_Initial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolSecondaryClaim_Amount_Installment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolSecondaryClaim_Amount_Installment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolSecondaryRemainingBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolSecondaryRemainingBalance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolSecondaryAmountBilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolSecondaryAmountBilled As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkPrintMonthlyClaimSecondary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrintMonthlyClaimSecondary As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSecondaryInsuranceProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondaryInsuranceProvider As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtInsured_name_first_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_first_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_name_mid_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_mid_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_name_last_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_last_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_name_suffx_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_name_suffx_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_street_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_street_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_city_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_city_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_state_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_state_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInsured_addr_zip_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsured_addr_zip_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlInsured_Gender_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInsured_Gender_sec As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dteInsured_Date_Birth_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteInsured_Date_Birth_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlRelationship_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship_sec As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEmployer_Name_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployer_Name_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dteDate_Effective_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDate_Effective_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dteDate_Canceled_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDate_Canceled_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGroup_Number_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroup_Number_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPolicy_Number_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolicy_Number_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dolLifetimeMax_sec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dolLifetimeMax_sec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNew As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtAddNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddNotes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNote As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtViewNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViewNotes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''litScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litScripts As Global.System.Web.UI.WebControls.Literal
End Class
