'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ContractStatus
    
    '''<summary>
    '''btnHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHidden As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtSessions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSessions As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''litPatientHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPatientHeader As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''txtLastNameSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastNameSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAccountNumSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChartNumSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChartNumSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblInitialPatAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialPatAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInitialPrimaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialPrimaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInitialSecondaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialSecondaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblContractMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractMonths As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblContractPatAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractPatAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblContractPrimaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractPrimaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblContractSecondaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractSecondaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilledMonthsPatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilledMonthsPatient As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilledPatAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilledPatAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilledMonthsPrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilledMonthsPrimary As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilledPrimaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilledPrimaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilledMonthsSecondary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilledMonthsSecondary As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilledSecondaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilledSecondaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRemainingMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemainingMonths As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRemainingPatAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemainingPatAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRemainingPrimaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemainingPrimaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRemainingSecondaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemainingSecondaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreditMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreditMonths As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreditPatAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreditPatAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreditPrimaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreditPrimaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCreditSecondaryAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreditSecondaryAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPatientLastPostDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientLastPostDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPrimaryLastPostDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrimaryLastPostDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSecondaryLastPostDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondaryLastPostDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccountBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccount0to30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccount0to30 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccount31to60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccount31to60 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccount61to90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccount61to90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccountOver90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountOver90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInsuranceBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInsuranceBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInsurance0to30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInsurance0to30 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInsurance31to60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInsurance31to60 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInsurance61to90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInsurance61to90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInsuranceOver90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInsuranceOver90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPatientBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPatient0to30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatient0to30 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPatient31to60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatient31to60 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPatient61to90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatient61to90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPatientOver90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientOver90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUndistBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndistBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUndist0to30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndist0to30 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUndist31to60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndist31to60 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUndist61to90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndist61to90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUndistOver90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndistOver90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPayoffBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayoffBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOptions As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litScripts As Global.System.Web.UI.WebControls.Literal
End Class
