'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmListManager
    
    '''<summary>
    '''frmListManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmListManager As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btnHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHidden As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hidTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidTableName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidMenuID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMenuID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidSessionsPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSessionsPrefix As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtSortCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSortCol As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''litNavDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNavDDL As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litDDLSelectedList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDDLSelectedList As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litNavTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNavTabs As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litSelectedListDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSelectedListDisplay As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litSelectedList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSelectedList As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litPaginationHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPaginationHeader As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litPagination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPagination As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ddlItemsPerPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlItemsPerPage As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''litCurrentPageInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCurrentPageInfo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''litBtnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBtnAdd As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnClearQuickSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearQuickSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtQuickSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuickSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearchClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSearchGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchGo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlColumnAdvSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlColumnAdvSearch1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlLogicAdvSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLogicAdvSearch1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtColumnAdvSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColumnAdvSearch1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlAndOrAdvSearch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAndOrAdvSearch2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlColumnAdvSearch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlColumnAdvSearch2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlLogicAdvSearch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLogicAdvSearch2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtColumnAdvSearch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColumnAdvSearch2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlAndOrAdvSearch3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAndOrAdvSearch3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlColumnAdvSearch3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlColumnAdvSearch3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlLogicAdvSearch3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLogicAdvSearch3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtColumnAdvSearch3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColumnAdvSearch3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlAndOrAdvSearch4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAndOrAdvSearch4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlColumnAdvSearch4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlColumnAdvSearch4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlLogicAdvSearch4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLogicAdvSearch4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtColumnAdvSearch4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColumnAdvSearch4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlAndOrAdvSearch5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAndOrAdvSearch5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlColumnAdvSearch5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlColumnAdvSearch5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlLogicAdvSearch5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLogicAdvSearch5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtColumnAdvSearch5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColumnAdvSearch5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FLMGridList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FLMGridList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rprGridHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rprGridHeader As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rprGridListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rprGridListing As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''litTopScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopScripts As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litScripts As Global.System.Web.UI.WebControls.Literal
End Class
